spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ssm_crud?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    #\u5207\u6362\u6570\u636E\u6E90
    type: com.alibaba.druid.pool.DruidDataSource
    #druid\u914D\u7F6E
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #\u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1\uFF0C'wall'\u7528\u4E8E\u9632\u706B\u5899\uFF0C\u4F7F\u7528\u7684logback\u8BB0\u5F55\u65E5\u5FD7
    filters: stat,wall,logback
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    #\u5F00\u542F\u6267\u884C.sql\u6587\u4EF6\uFF0C\u9ED8\u8BA4\u6587\u4EF6\u540D\u5FC5\u987B\u662Fschema.sql\u6216schema-all.sql
#    initialization-mode: always
    #\u6267\u884C\u81EA\u5B9A\u4E49\u7684.sql\u6587\u4EF6
#    schema:
#      - classpath:department.sql
